spring.application.name=delivery

spring.security.user.password=test
jwt.secret=${JWT_SECRET_BASE64:Zm9vZGJveC1kZWxpdmVyeS1qd3Qtc2VjcmV0LWtleS0zMi1ieXRlcw==}

spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/delivery}
spring.datasource.username=${DATASOURCE_LOGIN:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

image.upload-dir=${IMAGES_DIR}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

yandex.map.api.key=${YANDEX_MAP_API_KEY}
yandex.map.baseurl=https://geocode-maps.yandex.ru/v1
yandex.suggest.key=${SUGGEST_MAP_KEY}
yandex.suggest.url=${YANDEX_SUGGEST_URL}

sms.ru.api.key = ${SMS_RU_API}

cloud.payments.public.id = ${CLOUDPAYMENTS_PUBLIC_ID}
cloud.payments.secret = ${CLOUDPAYMENTS_SECRET}

server.port=${SERVER_PORT:8080}

telegram.token=${TELEGRAM_TOKEN}
telegram.bot_name=${TELEGRAM_BOT_NAME}

base_url=${BASE_URL}

s3.endpoint=${S3_ENDPOINT:https://storage.yandexcloud.net}
s3.region=${S3_REGION:ru-central1}
s3.access-key=${S3_ACCESS_KEY}
s3.secret-key=${S3_SECRET_KEY}
s3.bucket=${S3_BUCKET}
s3.path-style-access=${S3_PATH_STYLE_ACCESS:true}
