package ru.foodbox.delivery.modules.catalogimport.domain

enum class CatalogImportErrorCode {
    MISSING_REQUIRED_FIELD,
    INVALID_BOOLEAN,
    INVALID_NUMBER,
    INVALID_ENUM,
    DUPLICATE_KEY_IN_FILE,
    CATEGORY_NOT_FOUND,
    PARENT_CATEGORY_NOT_FOUND,
    MODIFIER_GROUP_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    ENTITY_ALREADY_EXISTS,
    INVALID_MIN_MAX_RULE,
    AMBIGUOUS_MATCH,
    INVALID_RELATION,
    PERSISTENCE_ERROR,
}
